Style:
  Background color: "#32292F"
  Default collider color: "#7389AEB4"
  Default joint color: "#C16E70B4"
  Body selection color: "#FED766B4"
  Collider selection color: "#A0CED9B4"
  Quad tree color: "#E5D0CC"
  Contact color: "#252627"
  Normal color: "#F2EFE9"
  Ray cast color: "cyan"
  Selection outline color: "#FED766"
  Distance joint stretch color: "#3E7CB1"
  Distance joint relax color: "#D1E3DD"
  Distance joint compress color: "#C16E70"
  Island colors:
    - "#FEF6C9"
    - "#D4DFC7"
    - "#96C0B7"
    - "#878E88"
    - "#725752"